[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
identity_registry = "2pELseyWXsBRXWBEPZAMqXsyBsRKADAz6LhSgV8Szc2e"
reputation_registry = "A99rMj3Nu975ShFzyhPyae9raBPxDYQiwi8g6RPC73Mp"
validation_registry = "9wwukuFjurWGDXREvnyBLPyePP4wssP5HCuRd1FJsaKc"
vote_registry = "EKqkjsLHK8rFr7pdySSFKZjhQfnEWeVqPRdZekw1t1j6"
token_staking = "4JNxNBFEH3BD6VRjQoi2pNDpbEa8L46LKbHnUTrdAWeL"

[programs.devnet]
identity_registry = "2pELseyWXsBRXWBEPZAMqXsyBsRKADAz6LhSgV8Szc2e"
reputation_registry = "A99rMj3Nu975ShFzyhPyae9raBPxDYQiwi8g6RPC73Mp"
validation_registry = "9wwukuFjurWGDXREvnyBLPyePP4wssP5HCuRd1FJsaKc"
vote_registry = "EKqkjsLHK8rFr7pdySSFKZjhQfnEWeVqPRdZekw1t1j6"
token_staking = "4JNxNBFEH3BD6VRjQoi2pNDpbEa8L46LKbHnUTrdAWeL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "jest"
